Repository maiste/equinoxe, pull requests merged in 2022-01, with the labels that each got.

#48 First example
  examples/dune
  examples/example_1.ml
Labels: T-Doc, G-Meta, no-changelog

#49 Http-lwt-client
  dune-project
  equinoxe.opam
  src/lib/dune
  src/lib/equinoxe.ml
  src/lib/http_api.ml
  src/lib/http_api.mli
  tests/lib/dune
  tests/lib/helper_server.ml
Labels: T-Bug, no-changelog

#50 Optional package
  dune-project
  equinoxe.opam
  examples/dune
  examples/example_1.ml
  src/bin/dune
  src/bin/utils.ml
  src/lib/callapi.ml
  src/lib/dune
  src/lib/equinoxe.ml
  src/lib/equinoxe_hlc.ml
  src/lib/equinoxe_hlc.mli
  src/lib/equinoxe_intf.ml
  src/lib/equinoxe_piaf.ml
  src/lib/equinoxe_piaf.mli
  tests/lib/backend.ml
  tests/lib/callapi.ml
  tests/lib/dune
Labels: T-Bug, no-changelog

#51 build: fix missing dependency
  dune-project
  equinoxe.opam
Labels: T-Bug, no-changelog

#44 Release 0.1.0
  CHANGES.md
Labels: P-High, T-Release

#52 Backport for next release
  CHANGES.md
  dune-project
  equinoxe.opam
Labels: G-Meta, P-High

#56 Correct typo in build system
  dune-project
  equinoxe.opam
Labels: T-Bug

#58 Fix a few typo and hide private module
  src/lib/equinoxe/equinoxe_intf.ml
Labels: T-Doc, no-changelog

#66 Stop exposing bin
  dune-project
  equinoxe-bin.opam
  src/bin/dune
Labels: type/refactor, no-changelog

#71 Convert modules to Friendly_api
  CHANGES.md
  dune-project
  equinoxe.opam
  examples/example_1.ml
  examples/example_2.ml
  src/bin/devices.ml
  src/bin/ips.ml
  src/bin/orga.ml
  src/bin/projects.ml
  src/bin/user.ml
  src/bin/utils.ml
  src/lib/backend/equinoxe_cohttp.ml
  src/lib/backend/equinoxe_cohttp.mli
  src/lib/backend/equinoxe_hlc.ml
  src/lib/backend/equinoxe_hlc.mli
  src/lib/equinoxe/dune
  src/lib/equinoxe/equinoxe.ml
  src/lib/equinoxe/equinoxe_intf.ml
Labels: priority/high, type/refactor, area/core
