Repository maiste/equinoxe, pull requests merged in 2022-02, with the labels that each got.

#73 Cleaner documentation
  .github/workflows/gh-pages.yml
Labels: type/doc, no-changelog

#70 Mock HTTP api
  CHANGES.md
  dune-project
  equinoxe.opam
  src/backend/dune
  src/backend/equinoxe_cohttp.ml
  src/backend/equinoxe_cohttp.mli
  src/backend/equinoxe_hlc.ml
  src/backend/equinoxe_hlc.mli
  src/bin/devices.ml
  src/bin/devices.mli
  src/bin/dune
  src/bin/ips.ml
  src/bin/ips.mli
  src/bin/main.ml
  src/bin/main.mli
  src/bin/orga.mli
  src/bin/projects.ml
  src/bin/projects.mli
  src/bin/user.ml
  src/bin/user.mli
  src/bin/utils.ml
  src/equinoxe/backend.ml
  src/equinoxe/dune
  src/equinoxe/equinoxe.ml
  src/equinoxe/equinoxe.mli
  src/equinoxe/equinoxe_intf.ml
  src/lib/backend/equinoxe_hlc.mli
  tests/mock/dune
  tests/mock/equinoxe_mock.ml
  tests/mock/mock.ml
  tests/mock/mock_auth.ml
  tests/mock/mock_device.ml
  tests/mock/mock_errors.ml
  tests/mock/mock_orga.ml
  tests/mock/mock_project.ml
  tests/mock/mock_user.ml
Labels: type/tests, area/http, area/core

#74 Release 0.2.0
  CHANGES.md
Labels: type/release
